<?php 

$students = [
    1 => [
        'firstname' => "Seyma",
        'lastname' => "ACAR",
        'birthdate' => '13/07/2004',
        'group' => '56',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    2 => [
        'firstname' => "Noura",
        'lastname' => "ALI HASSAN",
        'birthdate' => '26/11/2005',
        'group' => '12',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    3 => [
        'firstname' => "Mathys",
        'lastname' => "ALLEMAND",
        'birthdate' => '17/02/2005',
        'group' => '34',
        'photo' => '34_mathys_allemand.png',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    4 => [
        'firstname' => "Adam",
        'lastname' => "AMMARI",
        'birthdate' => '22/10/2005',
        'group' => '34',
        'photo' => '34_adam_ammari.png',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    5 => [
        'firstname' => "Lauren",
        'lastname' => "ANIGNIKIN",
        'birthdate' => '18/08/2004',
        'group' => '56',
        'photo' => '56_lauren_anignikin.png',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    6 => [
        'firstname' => "Zakaria",
        'lastname' => "BAOUI",
        'birthdate' => '08/11/2005',
        'group' => '78',
        'photo' => '78_zakaria_baoui.png',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    7 => [
        'firstname' => "Amandine",
        'lastname' => "BATRIKIAN - - MASSIAS",
        'birthdate' => '23/06/2005',
        'group' => '12',
        'photo' => '12_amandine_batrikian.png',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    8 => [
        'firstname' => "Aurèle",
        'lastname' => "BECHET",
        'birthdate' => '11/11/2004',
        'group' => '56',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    9 => [
        'firstname' => "Emilie",
        'lastname' => "BECKER",
        'birthdate' => '20/09/2004',
        'group' => '78',
        'photo' => '78_emilie_becker.png',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    10 => [
        'firstname' => "Zaïna",
        'lastname' => "BENLYAZID",
        'birthdate' => '03/09/2005',
        'group' => '34',
        'photo' => '34_zaina_benlyazdi.png',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    11 => [
        'firstname' => "Sara",
        'lastname' => "BENSADOK-WOEHRLÉ",
        'birthdate' => '22/06/2005',
        'group' => '34',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    12 => [
        'firstname' => "Linus",
        'lastname' => "BLAIRON",
        'birthdate' => '20/03/2005',
        'group' => '34',
        'photo' => '34_linus_blairon.png',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    13 => [
        'firstname' => "Léa",
        'lastname' => "BOINEL",
        'birthdate' => '30/07/2004',
        'group' => '34',
        'photo' => '34_lea_boinel.png',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    14 => [
        'firstname' => "Milan",
        'lastname' => "BOKAN",
        'birthdate' => '22/04/2004',
        'group' => '78',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    15 => [
        'firstname' => "Célestin",
        'lastname' => "BOUY",
        'birthdate' => '30/11/2005',
        'group' => '12',
        'photo' => '12_celestion_bouy.png',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    16 => [
        'firstname' => "Lili-Rose",
        'lastname' => "BURGOS",
        'birthdate' => '23/01/2005',
        'group' => '56',
        'photo' => '56_lili-rose_burgos.png',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    17 => [
        'firstname' => "Axel",
        'lastname' => "CERF",
        'birthdate' => '29/11/2005',
        'group' => '78',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    18 => [
        'firstname' => "Louis",
        'lastname' => "CHERQUI",
        'birthdate' => '17/02/2004',
        'group' => '12',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    19 => [
        'firstname' => "Nathan",
        'lastname' => "CHLOE",
        'birthdate' => '08/04/2004',
        'group' => '56',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    20 => [
        'firstname' => "Jonas",
        'lastname' => "CORREIA",
        'birthdate' => '23/02/2004',
        'group' => '34',
        'photo' => '34_jonas_correia.png',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    21 => [
        'firstname' => "Armel",
        'lastname' => "COULIBALY",
        'birthdate' => '13/03/2005',
        'group' => '12',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    22 => [
        'firstname' => "Thomas",
        'lastname' => "DAVID",
        'birthdate' => '16/10/2004',
        'group' => '78',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    23 => [
        'firstname' => "Timéo",
        'lastname' => "DECUYPER",
        'birthdate' => '03/02/2004',
        'group' => '78',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    24 => [
        'firstname' => "Bryan",
        'lastname' => "DHÉNAUX",
        'birthdate' => '29/08/2005',
        'group' => '12',
        'photo' => '12_bryan_dhenaux.png',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    25 => [
        'firstname' => "Tabara",
        'lastname' => "DIA",
        'birthdate' => '17/02/2004',
        'group' => '12',
        'photo' => '12_tabara_dia.png',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    26 => [
        'firstname' => "Iuventin",
        'lastname' => "DIVIZA",
        'birthdate' => '16/10/2004',
        'group' => '12',
        'photo' => '12_Iuventin_diviza.png',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    27 => [
        'firstname' => "Leonie",
        'lastname' => "DROUAULT",
        'birthdate' => '22/04/2005',
        'group' => '56',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    28 => [
        'firstname' => "Sami",
        'lastname' => "EDDAHBI",
        'birthdate' => '08/01/2004',
        'group' => '12',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    29 => [
        'firstname' => "Thomas De Jess",
        'lastname' => "EFFEIND-ZOUROU",
        'birthdate' => '26/05/2005',
        'group' => '34',
        'photo' => '34_thomas_eiffend.png',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    30 => [
        'firstname' => "Antoni",
        'lastname' => "EIFFES",
        'birthdate' => '23/06/2005',
        'group' => '12',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    31 => [
        'firstname' => "Nawfal",
        'lastname' => "EL ISSAOUI",
        'birthdate' => '11/09/2004',
        'group' => '78',
        'photo' => '78_nawfal_elissaoui.png',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    32 => [
        'firstname' => "Victoire",
        'lastname' => "ESTEVAM",
        'birthdate' => '19/08/2005',
        'group' => '34',
        'photo' => '34_victoire_estevam.png',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    33 => [
        'firstname' => "Elden",
        'lastname' => "EVOUNG-DURAND",
        'birthdate' => '27/07/2004',
        'group' => '12',
        'photo' => '12_elden_evoung_durand.png',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    34 => [
        'firstname' => "Jeevons",
        'lastname' => "EYA-JR IQ",
        'birthdate' => '05/09/2005',
        'group' => '34',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    35 => [
        'firstname' => "Alban",
        'lastname' => "FAITOUT--FOURMIGUE",
        'birthdate' => '11/06/2004',
        'group' => '78',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    36 => [
        'firstname' => "Guilherme",
        'lastname' => "FERREIRA CAETANO",
        'birthdate' => '14/10/2004',
        'group' => '56',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    37 => [
        'firstname' => "Aymeric",
        'lastname' => "FORBAN",
        'birthdate' => '19/05/2005',
        'group' => '34',
        'photo' => '34_aymeric_forban.png',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    38 => [
        'firstname' => "Jason",
        'lastname' => "FUKIDI",
        'birthdate' => '13/04/2005',
        'group' => '12',
        'photo' => '12_jason_fukidi.png',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    39 => [
        'firstname' => "Janis",
        'lastname' => "GENE-VASLET",
        'birthdate' => '28/10/2004',
        'group' => '56',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    40 => [
        'firstname' => "Priscille",
        'lastname' => "GOENGONDA",
        'birthdate' => '23/06/2005',
        'group' => '34',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    41 => [
        'firstname' => "Mariana",
        'lastname' => "GONCALVES LIMA",
        'birthdate' => '08/02/2005',
        'group' => '34',
        'photo' => '34_mariana_goncalves_lima.png',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    42 => [
        'firstname' => "Alicia",
        'lastname' => "GOSSIÔME",
        'birthdate' => '09/05/2004',
        'group' => '78',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    43 => [
        'firstname' => "Gladys",
        'lastname' => "GRÉGOIRE",
        'birthdate' => '04/06/2004',
        'group' => '34',
        'photo' => '34_gladys_gregoire.png',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    44 => [
        'firstname' => "Elsa",
        'lastname' => "GRELL--REGEN",
        'birthdate' => '08/04/2005',
        'group' => '78',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    45 => [
        'firstname' => "Sasha",
        'lastname' => "GUILLET",
        'birthdate' => '07/11/2005',
        'group' => '12',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    46 => [
        'firstname' => "Cléa",
        'lastname' => "GUITTET",
        'birthdate' => '03/06/2004',
        'group' => '78',
        'photo' => '78_clea_guittet.png',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    47 => [
        'firstname' => "Lila",
        'lastname' => "HADRACHI DARRICARRERE",
        'birthdate' => '03/12/2005',
        'group' => '12',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    48 => [
        'firstname' => "Chériane",
        'lastname' => "HAMRARAS",
        'birthdate' => '31/01/2004',
        'group' => '34',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    49 => [
        'firstname' => "Ilyes",
        'lastname' => "JABOU",
        'birthdate' => '10/03/2005',
        'group' => '34',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    50 => [
        'firstname' => "Charlotte",
        'lastname' => "JEANVOINE",
        'birthdate' => '17/10/2004',
        'group' => '56',
        'photo' => '56_charlotte_jeanvoine.png',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    51 => [
        'firstname' => "Sami",
        'lastname' => "KAMLI",
        'birthdate' => '02/01/2005',
        'group' => '56',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    52 => [
        'firstname' => "Phil-Heaven",
        'lastname' => "KIAKAKA",
        'birthdate' => '18/11/2005',
        'group' => '78',
        'photo' => '78_phil-heaven_kiakaka.png',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    53 => [
        'firstname' => "Benita",
        'lastname' => "KUNZIKA ZUMBU",
        'birthdate' => '17/11/2005',
        'group' => '34',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    54 => [
        'firstname' => "Melia",
        'lastname' => "LACIN",
        'birthdate' => '25/07/2005',
        'group' => '78',
        'photo' => '78_melia_lacin.png',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    55 => [
        'firstname' => "Valentin",
        'lastname' => "LAGANT",
        'birthdate' => '14/12/2004',
        'group' => '56',
        'photo' => '56_valentin_lagant.png',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    56 => [
        'firstname' => "Lisa",
        'lastname' => "LAVANDEIRA",
        'birthdate' => '25/08/2004',
        'group' => '56',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    57 => [
        'firstname' => "Alexandre",
        'lastname' => "LEBON",
        'birthdate' => '25/03/2005',
        'group' => '56',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    58 => [
        'firstname' => "Raphaël",
        'lastname' => "LECLAIRE",
        'birthdate' => '28/05/2005',
        'group' => '78',
        'photo' => '78_raphael_leclaire.png',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    59 => [
        'firstname' => "Emma",
        'lastname' => "LEMOINE",
        'birthdate' => '08/04/2005',
        'group' => '78',
        'photo' => '78_emma_lemoine.png',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    60 => [
        'firstname' => "Flora",
        'lastname' => "LEROY",
        'birthdate' => '23/06/2004',
        'group' => '34',
        'photo' => '34_flora_leroy.png',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    61 => [
        'firstname' => "Naomi",
        'lastname' => "LODJRO",
        'birthdate' => '21/03/2005',
        'group' => '34',
        'photo' => '34_naomi_lodjro.png',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    62 => [
        'firstname' => "Abigaël",
        'lastname' => "MARTIN",
        'birthdate' => '01/01/2005',
        'group' => '78',
        'photo' => '78_abigael_martin.png',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    63 => [
        'firstname' => "Alban",
        'lastname' => "MARTIN",
        'birthdate' => '19/07/2005',
        'group' => '56',
        'photo' => '56_alban_martin.png',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    64 => [
        'firstname' => "Joshuoy",
        'lastname' => "MARTIN",
        'birthdate' => '10/07/2005',
        'group' => '78',
        'photo' => '78_joshuoy_martin.png',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    65 => [
        'firstname' => "Litéya",
        'lastname' => "MASSAMOUNA",
        'birthdate' => '06/12/2005',
        'group' => '34',
        'photo' => '34_liteya_massamouna.png',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    66 => [
        'firstname' => "Sergelie",
        'lastname' => "MEDE",
        'birthdate' => '25/07/2005',
        'group' => '78',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    67 => [
        'firstname' => "Matéo",
        'lastname' => "MEDICO",
        'birthdate' => '14/05/2005',
        'group' => '56',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    68 => [
        'firstname' => "Amina",
        'lastname' => "MEGHOUFEL",
        'birthdate' => '12/10/2004',
        'group' => '56',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    69 => [
        'firstname' => "Naïma",
        'lastname' => "MENDY",
        'birthdate' => '19/01/2005',
        'group' => '12',
        'photo' => '12_naima_mendy.png',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    70 => [
        'firstname' => "Lina",
        'lastname' => "MESSAOUI",
        'birthdate' => '15/10/2005',
        'group' => '12',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    71 => [
        'firstname' => "Alexandre",
        'lastname' => "MEUX",
        'birthdate' => '01/08/2004',
        'group' => '34',
        'photo' => '34_alexandre_meux.png',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    72 => [
        'firstname' => "Ange",
        'lastname' => "MEYNARD",
        'birthdate' => '03/10/2004',
        'group' => '12',
        'photo' => '12_ange_meynard.png',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    73 => [
        'firstname' => "Amin",
        'lastname' => "MILADI",
        'birthdate' => '26/11/2004',
        'group' => '12',
        'photo' => '12_amin_miladi.png',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    74 => [
        'firstname' => "Nathân",
        'lastname' => "MOUDIO BOUENYE",
        'birthdate' => '09/03/2005',
        'group' => '78',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    75 => [
        'firstname' => "Mathis",
        'lastname' => "MULLER",
        'birthdate' => '25/04/2004',
        'group' => '78',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    76 => [
        'firstname' => "Shiffer",
        'lastname' => "MUMBELA MULUME",
        'birthdate' => '29/07/2005',
        'group' => '12',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    77 => [
        'firstname' => "Mathieu",
        'lastname' => "NALLACOUMOUPOULE",
        'birthdate' => '27/05/2005',
        'group' => '78',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    78 => [
        'firstname' => "Mohamed",
        'lastname' => "NDIAYE",
        'birthdate' => '29/12/2005',
        'group' => '56',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    79 => [
        'firstname' => "Henry",
        'lastname' => "N'KAKOU",
        'birthdate' => '01/06/2004',
        'group' => '78',
        'photo' => '78_henry_nkakou.png',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    80 => [
        'firstname' => "Kali",
        'lastname' => "NUTTIN-NARCISI",
        'birthdate' => '10/07/2004',
        'group' => '12',
        'photo' => '12_kali_nuttin_narcisi.png',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    81 => [
        'firstname' => "Camil",
        'lastname' => "OUAREM",
        'birthdate' => '15/09/2004',
        'group' => '56',
        'photo' => '56_camil_ouarem.png',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    82 => [
        'firstname' => "Ayoub",
        'lastname' => "OULED MABTOUL",
        'birthdate' => '07/01/2005',
        'group' => '12',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    83 => [
        'firstname' => "Yasmine",
        'lastname' => "OULMI",
        'birthdate' => '13/09/2005',
        'group' => '12',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    84 => [
        'firstname' => "Lucas",
        'lastname' => "PERDU",
        'birthdate' => '13/02/2005',
        'group' => '78',
        'photo' => '78_lucas_perdu.png',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    85 => [
        'firstname' => "Nicolas",
        'lastname' => "PERRIN",
        'birthdate' => '11/04/2005',
        'group' => '56',
        'photo' => '56_nicolas_perrin.png',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    86 => [
        'firstname' => "Louna",
        'lastname' => "PICHERIE",
        'birthdate' => '21/10/2005',
        'group' => '12',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    87 => [
        'firstname' => "Lucas",
        'lastname' => "PIEDADE",
        'birthdate' => '16/02/2005',
        'group' => '56',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    88 => [
        'firstname' => "Félix",
        'lastname' => "PLUCHE",
        'birthdate' => '03/04/2004',
        'group' => '34',
        'photo' => '34_felix_pluche.png',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    89 => [
        'firstname' => "Elyah",
        'lastname' => "RAKOTONIRINA",
        'birthdate' => '10/06/2005',
        'group' => '78',
        'photo' => '78_elyah_rakotonirina.png',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    90 => [
        'firstname' => "Sofia",
        'lastname' => "RAMDANI",
        'birthdate' => '07/12/2004',
        'group' => '34',
        'photo' => '34_sofia_ramdani.png',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    91 => [
        'firstname' => "Audrey",
        'lastname' => "RAMPARANY",
        'birthdate' => '28/07/2004',
        'group' => '12',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    92 => [
        'firstname' => "Aurore",
        'lastname' => "REGNIER",
        'birthdate' => '07/02/2005',
        'group' => '78',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    93 => [
        'firstname' => "Ambre",
        'lastname' => "REIGNEAU",
        'birthdate' => '30/11/2005',
        'group' => '56',
        'photo' => '56_ambre_reigneau.png',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    94 => [
        'firstname' => "Tom",
        'lastname' => "ROCHE",
        'birthdate' => '08/09/2005',
        'group' => '78',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    95 => [
        'firstname' => "Ahinoa",
        'lastname' => "RUIZ",
        'birthdate' => '28/05/2005',
        'group' => '56',
        'photo' => '56_ahinoa_ruiz.png',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    96 => [
        'firstname' => "Sarah",
        'lastname' => "SAUSSET",
        'birthdate' => '30/05/2004',
        'group' => '34',
        'photo' => '34_sarah_sausset.png',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    97 => [
        'firstname' => "Yanis",
        'lastname' => "SINGER",
        'birthdate' => '03/11/2005',
        'group' => '56',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    98 => [
        'firstname' => "Gabriel",
        'lastname' => "SINGPRASEUTH",
        'birthdate' => '13/11/2004',
        'group' => '34',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    99 => [
        'firstname' => "Hata",
        'lastname' => "SISSOKO",
        'birthdate' => '09/11/2005',
        'group' => '56',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    100 => [
        'firstname' => "Rita",
        'lastname' => "TABA TONDUKA",
        'birthdate' => '04/11/2004',
        'group' => '56',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    101 => [
        'firstname' => "Jérémy",
        'lastname' => "TAMOM",
        'birthdate' => '02/08/2005',
        'group' => '12',
        'photo' => '12_jeremy_tamon.png',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    102 => [
        'firstname' => "Alexis",
        'lastname' => "TISON",
        'birthdate' => '22/09/2005',
        'group' => '56',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    103 => [
        'firstname' => "Andoniaina",
        'lastname' => "TOMBOZAZA",
        'birthdate' => '08/03/2005',
        'group' => '56',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    104 => [
        'firstname' => "Noam",
        'lastname' => "TRANCHANT",
        'birthdate' => '06/05/2005',
        'group' => '56',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    105 => [
        'firstname' => "Adam",
        'lastname' => "TSOURIA BELAID",
        'birthdate' => '11/03/2004',
        'group' => '78',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    106 => [
        'firstname' => "Tom",
        'lastname' => "VIGUIE",
        'birthdate' => '28/06/2004',
        'group' => '34',
        'photo' => '34_tom_viguie.png',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
    107 => [
        'firstname' => "Charles",
        'lastname' => "VILAINE",
        'birthdate' => '04/09/2004',
        'group' => '12',
        'photo' => '12_charles_vilaine.png',
        'description' => "Je suis un brillant élève de l'IUT Sénart Fontainebleau. Je suis passionné par le WEB et la création numérique.", 
    ],
];
